version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: tasks
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: tasks

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${TARGET:-dev}
    ports:
      - 5000:5000
    environment:
      env_file: ./system_configs/.env
    volumes:
      - ./:/app
    depends_on:
      - mongo
