version: "3.8"

services:
  mongo_tests:
    image: mongo:latest
    container_name: mongo_tests
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test_db
