name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        python -m pip install --upgrade pip
        python -m pip install -U pyOpenSSL cryptography
        pip install --no-cache pipenv
        pipenv install --system --deploy --dev
        make deploy
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
